// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

/*
Package data is a generated protocol buffer package.

It is generated from these files:
	data.proto

It has these top-level messages:
	Message
*/
package data

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageType int32

const (
	MessageType_UNKNOWN MessageType = 0
	MessageType_TEXT    MessageType = 1
	MessageType_IMAGE   MessageType = 2
	MessageType_VIDEO   MessageType = 3
)

var MessageType_name = map[int32]string{
	0: "UNKNOWN",
	1: "TEXT",
	2: "IMAGE",
	3: "VIDEO",
}
var MessageType_value = map[string]int32{
	"UNKNOWN": 0,
	"TEXT":    1,
	"IMAGE":   2,
	"VIDEO":   3,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Message struct {
	MessageId uint64      `protobuf:"varint,1,opt,name=MessageId" json:"MessageId,omitempty"`
	Type      MessageType `protobuf:"varint,2,opt,name=Type,enum=data.MessageType" json:"Type,omitempty"`
	Content   string      `protobuf:"bytes,3,opt,name=Content" json:"Content,omitempty"`
	From      string      `protobuf:"bytes,4,opt,name=From" json:"From,omitempty"`
	FileID    string      `protobuf:"bytes,5,opt,name=FileID" json:"FileID,omitempty"`
	Timestamp int64       `protobuf:"varint,6,opt,name=Timestamp" json:"Timestamp,omitempty"`
	UID       int64       `protobuf:"varint,7,opt,name=UID" json:"UID,omitempty"`
	Channel   string      `protobuf:"bytes,8,opt,name=Channel" json:"Channel,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetMessageId() uint64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *Message) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN
}

func (m *Message) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Message) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Message) GetFileID() string {
	if m != nil {
		return m.FileID
	}
	return ""
}

func (m *Message) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Message) GetUID() int64 {
	if m != nil {
		return m.UID
	}
	return 0
}

func (m *Message) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "data.Message")
	proto.RegisterEnum("data.MessageType", MessageType_name, MessageType_value)
}

func init() { proto.RegisterFile("data.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xdd, 0x66, 0x9b, 0x34, 0x53, 0x90, 0x75, 0x0e, 0x32, 0x07, 0x0f, 0x41, 0x10, 0x82,
	0x87, 0x1e, 0xf4, 0xe6, 0x4d, 0x4c, 0x2a, 0x8b, 0x34, 0x85, 0x90, 0xaa, 0xd7, 0x95, 0x2e, 0x5a,
	0x68, 0xfe, 0xd0, 0xec, 0xc5, 0x2f, 0xeb, 0x67, 0x91, 0x1d, 0x57, 0xda, 0xdb, 0xef, 0xfd, 0x1e,
	0xec, 0x3c, 0x16, 0x60, 0x6b, 0x9c, 0x59, 0x0c, 0x87, 0xde, 0xf5, 0x28, 0x3d, 0x5f, 0xff, 0x08,
	0x48, 0x56, 0x76, 0x1c, 0xcd, 0xa7, 0xc5, 0x2b, 0x48, 0x03, 0xea, 0x2d, 0x89, 0x4c, 0xe4, 0xb2,
	0x3e, 0x0a, 0xbc, 0x01, 0xd9, 0x7c, 0x0f, 0x96, 0x26, 0x99, 0xc8, 0xcf, 0xef, 0x2e, 0x16, 0xfc,
	0x54, 0xa8, 0x7d, 0x51, 0x73, 0x8d, 0x04, 0xc9, 0x53, 0xdf, 0x39, 0xdb, 0x39, 0x8a, 0x32, 0x91,
	0xa7, 0xf5, 0x7f, 0x44, 0x04, 0xb9, 0x3c, 0xf4, 0x2d, 0x49, 0xd6, 0xcc, 0x78, 0x09, 0xf1, 0x72,
	0xb7, 0xb7, 0xba, 0xa0, 0x29, 0xdb, 0x90, 0xfc, 0x94, 0x66, 0xd7, 0xda, 0xd1, 0x99, 0x76, 0xa0,
	0x38, 0x13, 0x79, 0x54, 0x1f, 0x05, 0x2a, 0x88, 0x36, 0xba, 0xa0, 0x84, 0xbd, 0x47, 0xbe, 0xfa,
	0x65, 0xba, 0xce, 0xee, 0x69, 0x16, 0xae, 0xfe, 0xc5, 0xdb, 0x07, 0x98, 0x9f, 0x8c, 0xc4, 0x39,
	0x24, 0x9b, 0xea, 0xa5, 0x5a, 0xbf, 0x55, 0xea, 0x0c, 0x67, 0x20, 0x9b, 0xf2, 0xbd, 0x51, 0x02,
	0x53, 0x98, 0xea, 0xd5, 0xe3, 0x73, 0xa9, 0x26, 0x1e, 0x5f, 0x75, 0x51, 0xae, 0x55, 0xf4, 0x11,
	0xf3, 0x4f, 0xdd, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x83, 0xde, 0x46, 0x37, 0x01, 0x00,
	0x00,
}
